In [4]:
# Kjør cellen nedenfor før du starter oppgavene
import numpy as np

# 1a
A = np.array([[8, -1], [-7, 1]])
print(A)

[[ 8 -1]
 [-7  1]]


In [6]:
# 1b
f = np.array([[0],[1140]])
print(f)

[[   0]
 [1140]]


In [7]:
# 1c
B = np.array([[-5, 0], [1.5, 0.2]])
print(B)

[[-5.   0. ]
 [ 1.5  0.2]]


In [8]:
# 1d
g = np.array([[1],[0]])
s = np.linalg.inv(A)@g
print(s)
r = B@s
print(r)

[[1.]
 [7.]]
[[-5. ]
 [ 2.9]]


In [9]:
# 1e
f_fuel_perkWh = 1

In [11]:
# 2a
x1 = 2000
y1 = 1100
y2 = 220
y1e = 1000
y2e = 110

x_mass_steel = y1/(y1+y2)
x_econ_steel = y1*y1e/(y1*y1e+y2*y2e)
print(x_mass_steel, "\n", x_econ_steel)

0.8333333333333334 
 0.9784735812133072


In [12]:
# 2b
CO2 = 2000
SO2 = 150
PM10 = 0.2

steel_hq_CO2 = CO2 * x_econ_steel / y1
steel_hq_SO2 = SO2 * x_econ_steel / y1
steel_hq_PM10 = PM10 * x_econ_steel / y1
print(steel_hq_CO2, '\n', steel_hq_SO2, '\n', steel_hq_PM10)

1.7790428749332858 
 0.13342821561999643 
 0.0001779042874933286


In [13]:
# 3
milk = 133000 # l
meat = 5430 # kg
heif = 1 # stk

price_milk = 4
price_meat = 40
price_heif = 11250

flow_milk = milk * price_milk
flow_meat = meat * price_meat
flow_heif = heif * price_heif

tot_flow = flow_milk + flow_meat + flow_heif

w_milk = flow_milk / tot_flow
w_meat = flow_meat / tot_flow
w_heif = flow_heif / tot_flow

food = -60000
fuel = -3900
fert = -3195
el = -26000

CO2e_food = 0.63
CO2e_fuel = 0.25
CO2e_fert = 1.88
CO2e_el = 0.05

CO2 = 9880 * 1
CH4 = 5270 * 34
U = CO2 + CH4

A = np.array([[1, 0, 0, 0, food*w_milk, food*w_meat, food*w_heif], 
             [0, 1, 0, 0, fuel*w_milk, fuel*w_meat, fuel*w_heif], 
             [0, 0, 1, 0, fert*w_milk, fert*w_meat, fert*w_heif], 
             [0, 0, 0, 1, el*w_milk, el*w_meat, el*w_heif], 
             [0, 0, 0, 0, milk, 0, 0], 
             [0, 0, 0, 0, 0, meat, 0],  
             [0, 0, 0, 0, 0, 0, heif]])

B = np.array([CO2e_food, CO2e_fuel, CO2e_fert, CO2e_el, U*w_milk, U*w_meat, U*w_heif])

f = np.array([0, 0, 0, 0, 1, 0, 0])

R = B@np.linalg.inv(A)@f
CO2melk = R
print(CO2melk)


1.2368550200539155
